# Generated by Django 2.0.3 on 2018-04-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='country',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='email1',
            field=models.EmailField(default=None, max_length=100, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='agent',
            name='email2',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Second email address'),
        ),
        migrations.AddField(
            model_name='agent',
            name='email3',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Third email address'),
        ),
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='office',
            field=models.CharField(default=None, max_length=200, verbose_name='Apartment/Office'),
        ),
        migrations.AddField(
            model_name='agent',
            name='other_agent_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_num1',
            field=models.IntegerField(default=None, max_length=20, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_num2',
            field=models.IntegerField(blank=True, default=None, max_length=20, verbose_name='Alternative phone number'),
        ),
        migrations.AddField(
            model_name='agent',
            name='postal_code',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='province',
            field=models.CharField(blank=True, max_length=200, verbose_name='Province/State'),
        ),
        migrations.AddField(
            model_name='agent',
            name='street',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='website',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
