# Generated by Django 2.0.3 on 2018-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20180407_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone_num1',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_num2',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Alternative phone number'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
