# Generated by Django 2.0.3 on 2018-04-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20180408_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('not approved', 'not approved'), ('new agent', 'new agent'), ('approved', 'approved')], default='new agent', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Agent')),
            ],
        ),
    ]
